# Generated by Django 4.1.1 on 2022-10-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_customuser_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='avatar',
            new_name='image',
        ),
    ]
