# Generated by Django 4.1.1 on 2022-10-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_avatar_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='likes',
            field=models.ManyToManyField(blank=True, to='api.post'),
        ),
    ]
